// Do not edit. This file is machine generated by the Resource DLL Wizard.

library o2;

{ITE} {DFMFileType} {uAbout.dfm}
{ITE} {DFMFileType} {uFilePropsDlg.dfm}
{ITE} {DFMFileType} {uGetPassword.dfm}
{ITE} {DFMFileType} {uHTMLExport.dfm}
{ITE} {DFMFileType} {uMain.dfm}
{ITE} {DFMFileType} {uObjPropsDlg.dfm}
{ITE} {DFMFileType} {uPrintPreview.dfm}
{ITE} {DFMFileType} {uRelationPropsDlg.dfm}
{ITE} {DFMFileType} {uReplaceDlg.dfm}
{ITE} {DFMFileType} {uRTFViewer.dfm}
{ITE} {DFMFileType} {uRulePropsDlg.dfm}
{ITE} {DFMFileType} {uSetPassword.dfm}
{ITE} {RCFileType} {o2_DRC.rc}

{$R 'uAbout.dfm' 'AboutForm:TForm'}
{$R 'uFilePropsDlg.dfm' 'FilePropsDlg:TForm'}
{$R 'uGetPassword.dfm' 'GetPasswordDlg:TForm'}
{$R 'uHTMLExport.dfm' 'HTMLExport:TForm'}
{$R 'uMain.dfm' 'MainForm:TForm'}
{$R 'uObjPropsDlg.dfm' 'ObjPropsDlg:TForm'}
{$R 'uPrintPreview.dfm' 'PrintPreview:TForm'}
{$R 'uRelationPropsDlg.dfm' 'RelationPropsDlg:TForm'}
{$R 'uReplaceDlg.dfm' 'ReplaceDlg:TForm'}
{$R 'uRTFViewer.dfm' 'RTFViewer:TForm'}
{$R 'uRulePropsDlg.dfm' 'RulePropsDlg:TForm'}
{$R 'uSetPassword.dfm' 'SetPasswordDlg:TForm'}
{$R 'o2_DRC.res' 'o2_DRC.rc'}

{$E ITA}

begin
end.
